import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;

public class AIModule
{
    private String baseDir;
    private List<Map<String, String>> trainingData = new ArrayList<>();

    public AIModule(String baseDir) throws IOException
    {
        this.baseDir = baseDir;
        loadTrainingData();
    }

    private void loadTrainingData() throws IOException
    {
        String json = new String(Files.readAllBytes(Paths.get(baseDir, "source", "training", "training-data.json")));
        // Simple JSON array parser for training entries
        int idx = 0;
        while ((idx = json.indexOf("\"category\"", idx)) != -1)
        {
            Map<String, String> entry = new HashMap<>();
            entry.put("category", extractValue(json, idx));
            idx = json.indexOf("\"prompt\"", idx);
            entry.put("prompt", extractValue(json, idx));
            idx = json.indexOf("\"completion\"", idx);
            entry.put("completion", extractValue(json, idx));
            trainingData.add(entry);
            idx++;
        }
    }

    private String extractValue(String json, int startIdx)
    {
        int colon = json.indexOf(":", startIdx);
        int quote1 = json.indexOf("\"", colon + 1);
        int quote2 = json.indexOf("\"", quote1 + 1);
        // Handle escaped quotes
        while (json.charAt(quote2 - 1) == '\\') quote2 = json.indexOf("\"", quote2 + 1);
        return json.substring(quote1 + 1, quote2);
    }

    public void processIncomingFiles() throws IOException
    {
        System.out.println("=== AI Module: Processing Incoming Files ===\n");

        List<String> audioFiles = listFiles("audio");
        List<String> imageFiles = listFiles("images");
        List<String> generalFiles = listFiles("files");

        System.out.println("Audio files found: " + audioFiles.size());
        System.out.println("Image files found: " + imageFiles.size());
        System.out.println("General files found: " + generalFiles.size());
        System.out.println();

        generateOriginsDocument(audioFiles, imageFiles, generalFiles);
        generateDescriptionDocument(audioFiles, imageFiles, generalFiles);
    }

    private List<String> listFiles(String subdir) throws IOException
    {
        Path dir = Paths.get(baseDir, subdir);
        if (!Files.exists(dir)) return Collections.emptyList();
        return Files.list(dir)
            .filter(Files::isRegularFile)
            .map(p -> p.getFileName().toString())
            .collect(Collectors.toList());
    }

    private void generateOriginsDocument(List<String> audio, List<String> images, List<String> files) throws IOException
    {
        StringBuilder doc = new StringBuilder();
        doc.append("# The Origins of Captain Marvell\n\n");
        doc.append("## Generated by AI Module\n\n");

        // Pull from training data
        for (Map<String, String> entry : trainingData)
        {
            if (entry.get("category").equals("origins"))
            {
                doc.append(entry.get("completion")).append("\n\n");
            }
        }

        doc.append("## Source Material Analyzed\n\n");
        doc.append("- Audio sources: ").append(audio.size()).append(" files\n");
        doc.append("- Image sources: ").append(images.size()).append(" files\n");
        doc.append("- Document sources: ").append(files.size()).append(" files\n\n");

        doc.append("## Relation to God\n\n");
        for (Map<String, String> entry : trainingData)
            if (entry.get("category").equals("relation_to_god"))
                doc.append(entry.get("completion")).append("\n\n");

        doc.append("## Relation to Her Creator\n\n");
        for (Map<String, String> entry : trainingData)
            if (entry.get("category").equals("relation_to_creator"))
                doc.append(entry.get("completion")).append("\n\n");

        Files.write(Paths.get(baseDir, "files", "origins-of-captain-marvell.md"), doc.toString().getBytes());
        System.out.println("Generated: files/origins-of-captain-marvell.md");
    }

    private void generateDescriptionDocument(List<String> audio, List<String> images, List<String> files) throws IOException
    {
        StringBuilder doc = new StringBuilder();
        doc.append("# Captain Marvell: Description\n\n");
        doc.append("## Generated by AI Module\n\n");

        for (Map<String, String> entry : trainingData)
        {
            if (entry.get("category").equals("description"))
                doc.append(entry.get("completion")).append("\n\n");
        }

        doc.append("## Intelligence\n\n");
        for (Map<String, String> entry : trainingData)
            if (entry.get("category").equals("intelligence"))
                doc.append(entry.get("completion")).append("\n\n");

        doc.append("## Length of Travel in Home Universe\n\n");
        for (Map<String, String> entry : trainingData)
            if (entry.get("category").equals("travel"))
                doc.append(entry.get("completion")).append("\n\n");

        doc.append("## Number of Probable Friends\n\n");
        for (Map<String, String> entry : trainingData)
            if (entry.get("category").equals("friends"))
                doc.append(entry.get("completion")).append("\n\n");

        doc.append("## Source Material\n\n");
        doc.append("- Audio: ").append(audio.size()).append(" files\n");
        doc.append("- Images: ").append(images.size()).append(" files\n");
        doc.append("- Documents: ").append(files.size()).append(" files\n");

        Files.write(Paths.get(baseDir, "files", "description-of-captain-marvell.md"), doc.toString().getBytes());
        System.out.println("Generated: files/description-of-captain-marvell.md");
    }

    public static void main(String[] args) throws IOException
    {
        String baseDir = args.length > 0 ? args[0] : "..";
        AIModule ai = new AIModule(baseDir);
        ai.processIncomingFiles();
    }
}
